### ISSUE TITLE
Prepare requirements.txt file.

### ISSUE THREAD

**Issue by dawidsielski** [MNMdiagnostics/wgsqc#2]
Please prepare `requirements.txt` file in which you will specify what python packages (and their versions) are needed to run the code. 

More info:
1. https://pip.pypa.io/en/stable/user_guide/#requirements-files
2. https://medium.com/@boscacci/why-and-how-to-make-a-requirements-txt-f329c685181e

**Comment by rafalstepien** [comment]
File requirements.txt has been added.
